### ISSUE TITLE
[BUG] Add AppStream data for apps in Repo

### ISSUE THREAD

**Issue by ghost** [terrapkg/packages#1898] opened 2024-08-12 19:40 UTC
**Describe the bug**
Right now the apps in the Terra repo don't show up in GNOME Software or KDE Discover AFAIK so you can't install or uninstall them from there so you are forced to use the CLI to install apps from Terra. They can be updated from GNOME Software though as it uses PackageKit but they don't show up as an application in the updates tab, but instead as part of "System Updates." To fix this you can add appstream data for the applications in the repo so they can be installed and removed from the Software Center aka graphically which decreases the barrier to entry for Terra and they show up as applications in the updates tab so people may always know that they are being updated. This would also make it easier to find and explore the apps in this repo with GNOME Software / Discover and they would have an icon, screenshots, descriptions, and relevant links to their website or issue tracker.

**Screenshots**
![terra repo not showing up as source for crispy doom in gnome-software](https://github.com/user-attachments/assets/971e54ca-3f51-43ba-96f6-c046fbd9dbe7)

**Affected (please complete the following information):**
 - Distro: Fedora 40
 
**Additional context**
I have tested that for both crispy-doom and discord, Terra doesn't show up as a package source in GNOME Software. and have googled online if the Terra repo has appstream data but couldn't find any relevant results, I have also searched the Terra documentation online for the terms appstream, gnome-software, discover, and software center to also confirm if it already didn't have the data by searching for a mention of these words.

PS: Sorry for poor grammar.

**Comment by madonuko** [comment] 2024-08-13 11:00
Duplicate of #1327?

**Comment by ghost** [comment] 2024-08-13 19:35
> Duplicate of #1327?

Yes. Should I close the issue or will you do it yourself after marking this issue as duplicate?

**Closed as not planned** 2024-08-14 07:06 UTC
Labels: bug, duplicate
